"use client";

import Image from "next/image";
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, Cloud, Database, Globe2, Headphones, LifeBuoy, LockKeyhole, Mail, MapPin, Menu, Search, Server, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { Catalog, defaultCatalog } from "@/lib/catalog";
import { VpsNavigation } from "@/components/vps-navigation";

const portal = "https://app.cloudvps.bd";
const links = [{ href: "/domain", label: "Domains" }, { href: "/hosting", label: "Hosting" }, { href: "/vps", label: "VPS Servers" }, { href: "/ssl", label: "SSL" }, { href: "/why-us", label: "Why CloudVPS" }, { href: "/faq", label: "FAQ" }, { href: "/contact", label: "Contact" }];
type SearchResult = { domain: string; available: boolean; price?: number; error?: string };
const money = (n: number) => new Intl.NumberFormat("en-BD", { maximumFractionDigits: 2 }).format(n);

export function Shell({ current, children }: { current: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  // Static marketing pages use full navigation so Cloudflare can serve their HTML directly.
  /* eslint-disable @next/next/no-html-link-for-pages */
  return <div className="inner-site">
    <div className="announcement"><span className="pulse"/> Built for ideas that deserve to stay online <a href="/why-us">Meet CloudVPS <ArrowUpRight size={14}/></a></div>
    <header className="site-header"><a href="/" className="brand" aria-label="CloudVPS home"><Image src="/cloudvps-logo.png" width={220} height={46} alt="CloudVPS" priority/></a>
      <nav className={open ? "nav-links open" : "nav-links"} aria-label="Main navigation">{links.map(link => link.href === "/vps" ? <VpsNavigation key={link.href} current={current} onNavigate={() => setOpen(false)}/> : <a key={link.href} href={link.href} aria-current={current === link.href ? "page" : undefined} onClick={() => setOpen(false)}>{link.label}</a>)}</nav>
      <div className="header-actions"><a className="button button-dark header-cta" href={portal + "/login"}>Client login <ArrowUpRight size={16}/></a></div>
      <button className="mobile-menu" type="button" aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button>
    </header>
    <main>{children}</main>
    <footer className="footer"><div className="container footer-main"><div><a href="/"><Image src="/cloudvps-logo.png" width={170} height={36} alt="CloudVPS"/></a><p>Domains, web hosting, VPS and SSL solutions for what&apos;s next.</p></div><div><strong>Services</strong><a href="/domain">Domains</a><a href="/hosting">Hosting</a><a href="/vps">VPS Servers</a><a href="/bdix-vps">BDIX VPS</a><a href="/ssl">SSL Certificates</a></div><div><strong>Company</strong><a href="/why-us">Why CloudVPS</a><a href="/faq">FAQ</a><a href="/contact">Contact</a></div><div><strong>Account</strong><a href={portal + "/login"}>Client login</a><a href={portal}>Client portal</a><a href="mailto:support@cloudvps.bd">support@cloudvps.bd</a></div></div><div className="container footer-bottom"><span>© 2026 CloudVPS. All rights reserved.</span><span>Built for what&apos;s next.</span></div></footer>
  </div>;
}

function InnerHero({ eyebrow, title, accent, description, icon, children }: { eyebrow: string; title: string; accent: string; description: string; icon: React.ReactNode; children?: React.ReactNode }) {
  return <section className="inner-hero"><div className="inner-orbit inner-orbit-one"/><div className="inner-orbit inner-orbit-two"/><div className="container inner-hero-layout"><div><div className="eyebrow"><span className="eyebrow-line"/>{eyebrow}</div><h1>{title}<br/><em>{accent}</em></h1><p>{description}</p><div className="inner-hero-actions">{children}</div></div><div className="inner-hero-art" aria-hidden="true"><div className="art-halo"/><div className="art-icon">{icon}</div><span className="art-dot one"/><span className="art-dot two"/><span className="art-dot three"/></div></div></section>;
}

function SectionTitle({ kicker, title, description }: { kicker: string; title: string; description?: string }) {
  return <div className="inner-section-title"><span className="section-kicker">{kicker}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>;
}

function Closing({ title, text, href, action }: { title: string; text: string; href: string; action: string }) {
  return <section className="inner-closing"><div className="container"><div><span className="section-kicker">READY WHEN YOU ARE</span><h2>{title}</h2><p>{text}</p></div><a className="button button-cyan" href={href}>{action}<ArrowUpRight size={18}/></a></div></section>;
}

function DomainFinder() {
  const [domain, setDomain] = useState("");
  const [result, setResult] = useState<SearchResult | null>(null);
  const [searching, setSearching] = useState(false);
  async function check(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const value = domain.trim().toLowerCase();
    if (!/^(?=.{3,253}$)[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/.test(value)) {
      setResult({ domain: value, available: false, error: "Enter a valid domain, such as yourbrand.com.bd." }); return;
    }
    setSearching(true); setResult(null);
    try {
      const r = await fetch("/api/domain-check", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ domain: value }) });
      setResult(await r.json());
    } catch { setResult({ domain: value, available: false, error: "Search is temporarily unavailable. Please use the client portal." }); }
    finally { setSearching(false); }
  }
  return <div className="finder-panel"><div className="finder-panel-top"><span><Globe2 size={21}/> LIVE DOMAIN SEARCH</span><ShieldCheck size={20}/></div><h2>Find your place online.</h2><p>Type the complete name you want, including its extension.</p><form className="search-form" onSubmit={check}><Search size={20}/><input aria-label="Domain name" placeholder="yourbrand.com.bd" value={domain} onChange={e => setDomain(e.target.value)}/><button disabled={searching} type="submit">{searching ? "Checking..." : "Search"}</button></form><div className="finder-result" aria-live="polite">{result ? result.error ? <p className="search-error">{result.error} <a href={portal + "/order"}>Open portal</a></p> : <div className={result.available ? "search-result available" : "search-result"}><span><strong>{result.domain}</strong> {result.available ? "is available" : "is unavailable"}{result.available && Number.isFinite(result.price) ? ` · ৳${money(result.price!)}/yr` : ""}</span>{result.available && <a href={portal + "/order?domain=" + encodeURIComponent(result.domain)}>Continue <ArrowUpRight size={17}/></a>}</div> : <span>Search .bd, .com.bd, .com and many more extensions.</span>}</div></div>;
}

function PlanFallback({ type }: { type: "hosting" | "vps" }) {
  return <div className="catalog-fallback"><h3>Explore plans</h3><p>See the latest {type.toUpperCase()} plans in the client portal.</p><a href={portal + "/" + type}>View plans <ArrowUpRight size={17}/></a></div>;
}

export function DomainPage({ initialCatalog }: { initialCatalog?: Catalog }) {
  const catalog = initialCatalog ?? defaultCatalog;
  return <Shell current="/domain"><InnerHero eyebrow="DOMAINS / YOUR DIGITAL IDENTITY" title="Your name starts" accent="something bigger." description="Make it easy for people to find and remember you. Search your next domain and continue registration in the CloudVPS client portal." icon={<Globe2 size={125} strokeWidth={1.2}/>}><a className="button button-cyan" href="#search">Find a domain <ArrowRight size={17}/></a><a className="text-link" href={portal + "/domains/pricing"}>All extensions <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section finder-section" id="search"><div className="container finder-layout"><div><SectionTitle kicker="01 / FIND YOUR NAME" title="A great idea needs a great address." description="Check availability here, then choose the right name in the client portal. Your search carries through to the order page."/><div className="mini-benefits"><span><CheckCircle2/> Live availability</span><span><CheckCircle2/> Clear customer pricing</span><span><CheckCircle2/> Registration in the portal</span></div></div><DomainFinder/></div></section>
    <section className="inner-section tld-section"><div className="container"><SectionTitle kicker="02 / POPULAR EXTENSIONS" title="Find the ending that fits." description="Prices below come from the same customer storefront used by the CloudVPS app. Final pricing is confirmed before ordering."/><div className="tld-price-grid">{catalog?.domains?.length ? catalog.domains.map(t => <a className="tld-price-card" key={t.extension} href={portal + "/domains/pricing"}><span>{t.extension}</span><strong>৳{money(t.price)}</strong><small>first year <ArrowUpRight size={15}/></small></a>) : <a className="tld-price-card tld-price-fallback" href={portal + "/domains/pricing"}>View current domain prices <ArrowUpRight size={18}/></a>}</div></div></section>
    <section className="inner-section steps-section"><div className="container"><SectionTitle kicker="03 / HOW IT WORKS" title="From idea to online identity."/><div className="steps-grid"><div><b>01</b><h3>Search a name</h3><p>Enter the full domain name you want and check availability.</p></div><div><b>02</b><h3>Choose your domain</h3><p>Review the extension and current price before continuing.</p></div><div><b>03</b><h3>Complete your order</h3><p>Register and manage your domain in the CloudVPS client portal.</p></div></div></div></section>
    <Closing title="Your next name is waiting." text="Start with a domain you can build around." href="#search" action="Search a domain"/></Shell>;
}

export function HostingPage({ initialCatalog }: { initialCatalog?: Catalog }) {
  const catalog = initialCatalog ?? defaultCatalog;
  return <Shell current="/hosting"><InnerHero eyebrow="WEB HOSTING / BUILT TO LAUNCH" title="A better home" accent="for your website." description="Get your site online with cPanel hosting and the resources to match your next stage. Pick a plan below and finish setup in the client portal." icon={<Cloud size={136} strokeWidth={1.2}/>}><a className="button button-cyan" href="#plans">Explore plans <ArrowRight size={17}/></a><a className="text-link" href="/contact">Ask a question <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section service-intro"><div className="container"><SectionTitle kicker="01 / SIMPLY GET ONLINE" title="Everything in one place." description="Start with shared hosting for a website or a growing collection of sites. Select the package that matches your storage and feature needs."/><div className="benefit-grid"><div><Database/><h3>Space for your content</h3><p>Choose from plans with different storage allocations as your site grows.</p></div><div><LockKeyhole/><h3>Built for your site</h3><p>See each plan&apos;s included tools and features before placing an order.</p></div><div><Headphones/><h3>Help is close</h3><p>Questions about the right fit? Reach the CloudVPS team from the portal.</p></div></div></div></section>
    <section className="inner-section hosting-price-section" id="plans"><div className="container"><SectionTitle kicker="02 / CHOOSE YOUR PLAN" title="Hosting for your next step." description="Monthly customer prices are loaded from the storefront. Choose a card to open that exact plan in the CloudVPS checkout."/><div className="plan-grid">{catalog?.hosting?.length ? catalog.hosting.map((p, i) => <a className={"plan-card " + (p.featured ? "featured" : "")} href={p.url} key={p.name}><div className="plan-index">0{i + 1} / WEB HOSTING</div><h3>{p.name}</h3><div className="plan-price">৳{money(p.price)}<span> / month</span></div><div className="plan-divider"/><ul>{p.details.map(d => <li key={d}><Check size={17}/>{d}</li>)}</ul><span className="plan-button">Choose plan <ArrowUpRight size={17}/></span></a>) : <PlanFallback type="hosting"/>}</div><a className="all-link" href={portal + "/hosting"}>Compare all hosting plans <ArrowUpRight size={18}/></a></div></section>
    <section className="inner-section steps-section"><div className="container"><SectionTitle kicker="03 / GET STARTED" title="Three simple steps."/><div className="steps-grid"><div><b>01</b><h3>Compare plans</h3><p>Look at the storage, features and monthly price.</p></div><div><b>02</b><h3>Choose your domain</h3><p>Register a new name or use a domain you already have.</p></div><div><b>03</b><h3>Finish in the portal</h3><p>Create or sign in to your account and review the order.</p></div></div></div></section><Closing title="Ready to put your site online?" text="Choose a plan that fits your website today." href="#plans" action="View hosting plans"/></Shell>;
}

export function VpsPage({ initialCatalog }: { initialCatalog?: Catalog }) {
  const catalog = initialCatalog ?? defaultCatalog;
  return <Shell current="/vps"><InnerHero eyebrow="VPS SERVERS / MORE CONTROL" title="Power your" accent="next ambition." description="Give applications and demanding workloads room to grow. Compare VPS resources here, then configure your server in the client portal." icon={<Server size={128} strokeWidth={1.2}/>}><a className="button button-cyan" href="#plans">Explore VPS plans <ArrowRight size={17}/></a><a className="text-link" href="/contact">Talk to support <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section service-intro"><div className="container"><SectionTitle kicker="01 / BUILT FOR MORE" title="A server you can shape." description="Select the CPU, memory and storage that fit your application. Choose your datacenter and operating system while configuring the order."/><div className="benefit-grid"><div><Server/><h3>Dedicated resources</h3><p>Compare vCPU, RAM and storage across available plans.</p></div><div><MapPin/><h3>Location choice</h3><p>Explore Bangladesh and USA plans shown in the live storefront.</p></div><div><ShieldCheck/><h3>Full configuration</h3><p>Choose the operating system and available options before checkout.</p></div></div></div></section>
    <section className="inner-section vps-price-section" id="plans"><div className="container"><SectionTitle kicker="02 / FIND YOUR SERVER" title="Choose the power you need." description="These customer prices are loaded from the storefront. Select a card to open that VPS plan and location in the client portal."/><a className="bdix-home-link" href="/bdix-vps">সব Bangladesh BDIX packages ও use cases দেখুন <ArrowUpRight size={18}/></a><div className="vps-grid">{catalog?.vps?.length ? catalog.vps.map((p, i) => <a className="vps-card" href={p.url} key={p.name}><div className="vps-top"><Server size={25}/><span>0{i + 1} / CLOUD VPS</span></div><h3>{p.name}</h3><div className="vps-specs">{p.details.map(d => <span key={d}>{d}</span>)}</div><div className="vps-bottom"><span>From <strong>৳{money(p.price)}</strong> / month</span><ArrowUpRight size={23}/></div></a>) : <PlanFallback type="vps"/>}</div><a className="all-link light" href={portal + "/vps"}>Compare all VPS plans <ArrowUpRight size={18}/></a></div></section>
    <section className="inner-section steps-section"><div className="container"><SectionTitle kicker="03 / CONFIGURE IT YOUR WAY" title="From plan to running server."/><div className="steps-grid"><div><b>01</b><h3>Pick a plan</h3><p>Choose the resources and datacenter for your workload.</p></div><div><b>02</b><h3>Set your options</h3><p>Select an operating system and review available extras.</p></div><div><b>03</b><h3>Review your order</h3><p>Confirm the configuration and final total in the portal.</p></div></div></div></section><Closing title="Build on a stronger foundation." text="Find the VPS resources that fit your project." href="#plans" action="View VPS plans"/></Shell>;
}

const sslOptions = [
  { short: "DV", name: "Domain Validation", detail: "Verify control of the domain and enable HTTPS for a website.", best: "A straightforward certificate for a site or project.", href: portal + "/ssl/dv-ssl" },
  { short: "OV", name: "Organization Validation", detail: "Adds checks of the organization behind the website.", best: "A business that wants verified organization details.", href: portal + "/ssl/ov-ssl" },
  { short: "EV", name: "Extended Validation", detail: "Uses a more detailed organization verification process.", best: "An organization that needs a higher level of identity review.", href: portal + "/ssl/ev-ssl" },
  { short: "*", name: "Wildcard SSL", detail: "Covers a domain and its first-level subdomains, subject to the product terms.", best: "Several subdomains under one domain name.", href: portal + "/ssl/wildcard-ssl" },
];

export function SslPage() {
  return <Shell current="/ssl"><InnerHero eyebrow="SSL CERTIFICATES / TRUST ONLINE" title="Give your website" accent="a secure connection." description="Explore certificate options for your website. Compare current products and prices in the CloudVPS client portal before you order." icon={<ShieldCheck size={132} strokeWidth={1.2}/>}><a className="button button-cyan" href="#options">Explore options <ArrowRight size={17}/></a><a className="text-link" href={portal + "/ssl"}>See live prices <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section service-intro"><div className="container"><SectionTitle kicker="01 / WHY SSL" title="A more trusted way to connect." description="An SSL certificate helps protect information exchanged between a visitor's browser and your website by enabling HTTPS."/><div className="benefit-grid"><div><LockKeyhole/><h3>Encrypted connection</h3><p>HTTPS helps protect data while it travels between the browser and your site.</p></div><div><ShieldCheck/><h3>Right level of validation</h3><p>Choose domain or organization validation based on what your project needs.</p></div><div><Globe2/><h3>Room for subdomains</h3><p>Wildcard products are available when several subdomains need coverage.</p></div></div></div></section>
    <section className="inner-section ssl-options-section" id="options"><div className="container"><SectionTitle kicker="02 / FIND THE RIGHT FIT" title="SSL options at a glance." description="Explore the certificate types, then check the live product details and customer price in the CloudVPS app."/><div className="ssl-options-grid">{sslOptions.map(option => <a className="ssl-option-card" key={option.name} href={option.href}><span className="ssl-option-mark">{option.short}</span><h3>{option.name}</h3><p>{option.detail}</p><div className="ssl-option-best"><strong>Good for</strong><span>{option.best}</span></div><span className="ssl-option-action">View certificates <ArrowUpRight size={17}/></span></a>)}</div><a className="all-link" href={portal + "/ssl"}>Compare all SSL certificates and current prices <ArrowUpRight size={18}/></a></div></section>
    <section className="inner-section steps-section"><div className="container"><SectionTitle kicker="03 / HOW TO CHOOSE" title="Choose with confidence."/><div className="steps-grid"><div><b>01</b><h3>Pick validation</h3><p>Decide whether domain validation or organization verification fits your needs.</p></div><div><b>02</b><h3>Check coverage</h3><p>Look at the domains and subdomains covered by the individual product.</p></div><div><b>03</b><h3>Review in the portal</h3><p>Confirm certificate details, term and final price before ordering.</p></div></div></div></section>
    <Closing title="Ready to secure your site?" text="Compare the current SSL products and choose the one that fits." href={portal + "/ssl"} action="See SSL products"/></Shell>;
}

export function WhyPage() {
  return <Shell current="/why-us"><InnerHero eyebrow="WHY CLOUDVPS / ONE PLACE TO GROW" title="Built for every" accent="next step." description="Your online journey changes. CloudVPS brings domains, hosting, VPS and SSL together so you can choose the right foundation as your plans grow." icon={<ShieldCheck size={132} strokeWidth={1.2}/>}><a className="button button-cyan" href="#solutions">Explore the approach <ArrowRight size={17}/></a><a className="text-link" href="/contact">Contact us <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section service-intro" id="solutions"><div className="container"><SectionTitle kicker="01 / BUILT AROUND YOUR IDEAS" title="One place. More possibilities." description="Start small, launch confidently and add resources when your project needs them."/><div className="benefit-grid"><a href="/domain"><Globe2/><h3>Claim your name</h3><p>Find a domain that makes your idea easy to discover.</p><span>Explore domains <ArrowUpRight size={16}/></span></a><a href="/hosting"><Cloud/><h3>Launch a website</h3><p>Choose hosting resources for the site you are building.</p><span>Explore hosting <ArrowUpRight size={16}/></span></a><a href="/vps"><Server/><h3>Scale your work</h3><p>Move to VPS resources when you need more control.</p><span>Explore VPS <ArrowUpRight size={16}/></span></a></div></div></section>
    <section className="inner-section promise-section"><div className="container promise-layout"><div><SectionTitle kicker="02 / A CLEAR PATH FORWARD" title="Keep building without losing momentum." description="Use this site to discover your options and compare current customer prices. The client portal is where you place orders and manage your services."/><a className="button button-dark" href={portal}>Visit client portal <ArrowUpRight size={17}/></a></div><div className="promise-stack"><div><b>01</b><span><strong>Explore</strong><small>Compare domains, hosting and VPS in one familiar experience.</small></span></div><div><b>02</b><span><strong>Choose</strong><small>Open the exact package you want in the client portal.</small></span></div><div><b>03</b><span><strong>Manage</strong><small>Keep orders, billing and support together in your account.</small></span></div></div></div></section><Closing title="Let’s build what’s next." text="Find a service that matches the stage you are at." href="/domain" action="Explore services"/></Shell>;
}

const faqs = [
  { q: "Where do I manage my services?", a: "Sign in to the CloudVPS client portal to manage domains, hosting, VPS services, billing and support." },
  { q: "Can I search for a domain before signing up?", a: "Yes. Search on the Domains page. If the name is available, continue to the client portal with that name." },
  { q: "Are the prices on this site current?", a: "Plan and domain prices are loaded from the same public customer storefront used by the client portal. Confirm the final amount during checkout." },
  { q: "How do I choose between hosting and VPS?", a: "Web hosting is a straightforward way to launch a website. VPS gives you more control and dedicated resources for applications or larger workloads." },
  { q: "Where do I complete an order?", a: "Choose a plan here to open its order or configuration page at app.cloudvps.bd. Your account, payment and service management stay there." },
  { q: "Which SSL certificate should I choose?", a: "DV verifies domain control, OV and EV add organization checks, and Wildcard products can cover first-level subdomains. Review each product's details and current price in the client portal." },
  { q: "How can I get help?", a: "Use the support area in the client portal, or contact the CloudVPS team through the details on our Contact page." },
];

export function FaqPage() {
  return <Shell current="/faq"><InnerHero eyebrow="HELP CENTER / GOOD TO KNOW" title="Answers for the" accent="road ahead." description="Find the essentials about choosing a service, ordering and managing your CloudVPS account." icon={<LifeBuoy size={132} strokeWidth={1.2}/>}><a className="button button-cyan" href="#questions">Browse questions <ArrowRight size={17}/></a><a className="text-link" href="/contact">Need help? <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section faq-page-section" id="questions"><div className="container faq-page-layout"><div><SectionTitle kicker="POPULAR QUESTIONS" title="Good to know before you go." description="A quick guide to the services and how the landing site connects with your client account."/><a className="inline-link" href="/contact">Still have a question? Contact us <ArrowUpRight size={17}/></a></div><div className="faq-list">{faqs.map(item => <details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></div></section><Closing title="Need a hand choosing?" text="Our team can help you find the right next step." href="/contact" action="Contact CloudVPS"/></Shell>;
}

export function ContactPage() {
  return <Shell current="/contact"><InnerHero eyebrow="CONTACT / LET’S TALK" title="Here when you" accent="need a hand." description="Have a question about a domain, hosting plan, VPS or SSL? Reach the CloudVPS team through the channel that works for you." icon={<Headphones size={132} strokeWidth={1.2}/>}><a className="button button-cyan" href="#contact-options">Contact options <ArrowRight size={17}/></a><a className="text-link" href={portal + "/support"}>Open support portal <ArrowUpRight size={16}/></a></InnerHero>
    <section className="inner-section contact-section" id="contact-options"><div className="container"><SectionTitle kicker="GET IN TOUCH" title="Let’s find your next step." description="Use the client portal for account and service support. For general questions, email or call us."/><div className="contact-grid"><a href={portal + "/support"}><LifeBuoy/><small>EXISTING CUSTOMERS</small><h3>Support portal</h3><p>Ask about your active services and track support in your account.</p><span>Open portal <ArrowUpRight size={17}/></span></a><a href="mailto:support@cloudvps.bd"><Mail/><small>EMAIL US</small><h3>support@cloudvps.bd</h3><p>Send your question and tell us what you are planning to build.</p><span>Send email <ArrowUpRight size={17}/></span></a><a href="tel:+8801701007333"><Headphones/><small>CALL US</small><h3>01701-007333</h3><p>Speak with our team about the service you need.</p><span>Call now <ArrowUpRight size={17}/></span></a></div></div></section>
    <section className="inner-section contact-next"><div className="container"><SectionTitle kicker="EXPLORE FIRST" title="Know what you need?"/><div className="contact-next-links"><a href="/domain"><Globe2/> Domains <ArrowUpRight size={18}/></a><a href="/hosting"><Cloud/> Hosting <ArrowUpRight size={18}/></a><a href="/vps"><Server/> VPS Servers <ArrowUpRight size={18}/></a><a href="/ssl"><ShieldCheck/> SSL Certificates <ArrowUpRight size={18}/></a></div></div></section></Shell>;
}
